# Generated by Django 4.1.3 on 2022-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(default='', upload_to='')),
                ('artist', models.CharField(max_length=50)),
                ('song_name', models.CharField(max_length=50)),
            ],
        ),
    ]
