# Generated by Django 4.1.3 on 2022-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_mp3', '0003_alter_song_artist_alter_song_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='player_mp3/static/media/', verbose_name='Аудиодорожка'),
        ),
    ]
