# Generated by Django 4.1.3 on 2022-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_mp3', '0004_alter_song_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='player_mp3.playlist'),
        ),
    ]
