# Generated by Django 4.1.3 on 2022-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_mp3', '0006_remove_song_playlist_playlist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='player_mp3.playlist'),
        ),
    ]
