# Generated by Django 4.1.3 on 2022-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_mp3', '0009_remove_song_playlist_song_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='queue',
            field=models.JSONField(null=True, verbose_name='Очередь'),
        ),
    ]
