# Generated by Django 4.1.3 on 2022-11-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_mp3', '0010_playlist_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='queue',
            field=models.JSONField(default=[], verbose_name='Очередь'),
        ),
    ]
